name: "pattern3_merge"
group_reduce: "any"

classes:
  - "白内障"
  - "硝子体混濁"
  - "星状硝子体症"
  - "VH"
  - "MH"
  - "分層黄斑円孔"
  - "黄斑偽円孔"
  - "網膜円孔"
  - "網膜裂孔"
  - "lattice"
  - "RRD"
  - "RD術後"
  - "黄斑変性"
  - "ドルーゼン(drusen)"
  - "CSC"
  - "糖尿病網膜症"
  - "NPDR"
  - "PDR"
  - "DME"
  - "PRP"
  - "レーザー後"
  - "網膜静脈分枝閉塞"
  - "網膜中心静脈閉塞"
  - "眼底出血"
  - "網膜変性"
  - "網膜色素変性"
  - "網脈絡膜変性"
  - "網脈絡膜萎縮"
  - "強度近視眼底"
  - "コーヌス"
  - "ERM"
  - "緑内障(gla)"
  - "視神経乳頭陥凹拡大"
  - "uveitis"
  - "サルコイドーシス"
  - "眼内悪性リンパ腫"
  - "硬性白斑"
  - "有髄神経線維"
  - "S1"
  - "S2"
  - "S3"
  - "S4"
  - "H1"
  - "H2"
  - "H3"
  - "H4"

label_groups:
  "網膜裂孔": ["網膜裂孔", "網膜裂孔PC後", "網膜裂孔術後"]
  "網膜円孔": ["網膜円孔", "網膜円孔PC後", "網膜萎縮性円孔"]
  "lattice": ["lattice", "lattice(PC後)"]
  "網膜静脈分枝閉塞": ["網膜静脈分枝閉塞", "BRVO_PC後"]
  "ERM": ["ERM", "ERM術後"]
  "黄斑偽円孔": ["黄斑偽円孔", "黄斑偽円孔術後"]
  "MH": ["MH", "黄斑円孔術後", "黄斑円孔PC後"]
  "黄斑変性": ["黄斑変性", "nAMD", "PCV"]
  "NPDR": ["mild_NPDR", "moderate_NPDR", "severe_NPDR"]
